language: elixir

elixir:
  - '1.6.4'

install:
  - sudo apt-get update
  - sudo apt-get install nodejs npm
  - npm install -g ganache-cli
  - mix local.rebar --force # for Elixir 1.3.0 and up
  - mix local.hex --force
  - mix deps.get